### ISSUE TITLE
Add columns to reference and describe the provenance of CDEs

### ISSUE THREAD

**Issue by matthewhorridge** [bmir-radx/radx-data-dictionary-specification#6]
It's generally the case that each field in a data dictionary corresponds to a Common Data Element (CDE).  We need some extra columns to provide a reference to the CDE, the source of the CDE etc.

Cc @pwrose and @graybeal

**Comment by graybeal** [comment]
Reference to the CDE should be required to be an identifier (an IRI/URL, since if it's a registered CDE it should have a unique identifier that is resolvable). Possibly that just the @id of the referenced item. 

I think there's a useful pattern for this in the DataCite description patterns, this is just a particular digital object that needs provenance.  But I understand not everyone likes the DataCite description patterns.

**Comment by pwrose** [comment]
@matthewhorridge you completed this issues with the new fields: Provenance and SeeAlso.
